### ISSUE TITLE
load() method times out on random albums

### ISSUE THREAD

**Issue by richard-ive** [jodal/pyspotify#119]
When trying to load albums, some fail due to timeout, but there doesn't seem to be any consistency. 1/2 of the albums for one artists will work and the other 1/2 wont.

```
richard@raspberrypi-> python
Python 2.7.3 (default, Jan 13 2013, 11:20:46) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import spotify
>>> sess = spotify.Session()
>>> sess.login('xxxxx','xxxxxxxx')
>>> sess.get_album('spotify:album:02Zb13fM8k04tRwTfMUhe9')
Album(u'spotify:album:02Zb13fM8k04tRwTfMUhe9')
>>> sess.get_album('spotify:album:02Zb13fM8k04tRwTfMUhe9').load(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0a1-py2.7-linux-armv6l.egg/spotify/album.py", line 63, in load
    return utils.load(self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0a1-py2.7-linux-armv6l.egg/spotify/utils.py", line 217, in load
    raise RuntimeError('Session must be logged in to load objects')
RuntimeError: Session must be logged in to load objects
>>> sess.process_events()
1059
>>> sess.get_album('spotify:album:02Zb13fM8k04tRwTfMUhe9').load(5)
Album(u'spotify:album:02Zb13fM8k04tRwTfMUhe9')
>>> sess.get_album('spotify:album:02Zb13fM8k04tRwTfMUhe9').load(5).name
u'Welcome Reality'
>>> sess.get_album('spotify:album:3ph1ceuYuayuzoIJzPQji2').load(5).name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0a1-py2.7-linux-armv6l.egg/spotify/album.py", line 63, in load
    return utils.load(self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0a1-py2.7-linux-armv6l.egg/spotify/utils.py", line 228, in load
    raise spotify.Timeout(timeout)
spotify.error.Timeout: Operation did not complete in 5.000s
>>> sess.get_album('spotify:album:4IBQvwIbtDluogvDe2qpaB').load(5).name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0a1-py2.7-linux-armv6l.egg/spotify/album.py", line 63, in load
    return utils.load(self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0a1-py2.7-linux-armv6l.egg/spotify/utils.py", line 228, in load
    raise spotify.Timeout(timeout)
spotify.error.Timeout: Operation did not complete in 5.000s
>>> sess.get_album('spotify:album:5VppVyy751PTQWrfJbrJ4H').load(5).name
u'Between The Devil & The Deep Blue Sea (Special Edition)'
>>> sess.get_album('spotify:album:2cRMVS71c49Pf5SnIlJX3U').load(5).name
u'Coexist'
>>> sess.get_album('spotify:album:6mulYcpWRDAiv7KIouWvyP').load(5).name
u'ONE BY ONE'
>>> sess.get_album('spotify:album:6mulYcpWRDAiv7KIouWvyP').load(5).name
u'ONE BY ONE'
>>> sess.get_album('spotify:album:02jqf49ws9bcTvXLPGtjbT').load(5).name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0a1-py2.7-linux-armv6l.egg/spotify/album.py", line 63, in load
    return utils.load(self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0a1-py2.7-linux-armv6l.egg/spotify/utils.py", line 228, in load
    raise spotify.Timeout(timeout)
spotify.error.Timeout: Operation did not complete in 5.000s
>>> sess.get_album('spotify:album:17orrZznh0gmxYtpNP47nK').load(5).name
u'Another Home'
>>> sess.connection_state
<ConnectionState.LOGGED_IN: 1>
>>> sess.connection_state
<ConnectionState.LOGGED_IN: 1>
>>> sess.process_events()
60000
>>> sess.connection_state
<ConnectionState.LOGGED_IN: 1>
>>> sess.connection_state
<ConnectionState.LOGGED_IN: 1>
>>> sess.process_events()
28873
>>> sess.connection_state
<ConnectionState.LOGGED_IN: 1>
>>> sess.get_album('spotify:album:5lnQLEUiVDkLbFJHXHQu9m').load(5).name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0a1-py2.7-linux-armv6l.egg/spotify/album.py", line 63, in load
    return utils.load(self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0a1-py2.7-linux-armv6l.egg/spotify/utils.py", line 228, in load
    raise spotify.Timeout(timeout)
spotify.error.Timeout: Operation did not complete in 5.000s
>>> sess.process_events()
9489
>>> sess.connection_state
<ConnectionState.LOGGED_IN: 1>
```

**Comment by jodal** [comment]
I've been working a bit on reproducing this issue with just libspotify and C, but don't want to hold of the 2.0.0 release anymore to wait for this. If this is a pyspotify issue, and not a libspotify issue, we can fix in a later bugfix release. If this is a libspotify bug, but can be worked around with some non-intrusive change, we can do that in a bugfix release. The current workaround of using `album.browse()` to get the album to load is not something I want to do in pyspotify as that adds lots of extra overhead and data fetching to every album fetch.

**Comment by jodal** [comment]
Closing as libspotify and pyspotify are dead. See #215 for details.
